name: "Hello Actions"
description: "Great Someone"
author: "octocat@github.com"
inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
runs:    
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "mic"
  color: "purple"
